### ISSUE TITLE
unable to login

### ISSUE THREAD

**Issue by migliori** [style-tools/browser-widget#2]
Hi,
Your tools look really awesome, but I can't login, I tried several basic things:
- clear local storage
- disable all chrome extensions
- tried with Github or Google login

Here's a screenshot of the browser console errors after trying to login:

![image](https://user-images.githubusercontent.com/7558100/93694650-b26fb280-fb0e-11ea-808f-53fb637600f9.png)

Additionally,https://style.tools/i.woff2 is blocked by CORS policy.

Thanks for your help

**Comment by galbaras** [comment]
Feels like this repository may have been abandoned. I keep being asked to log in, despite authorising successfully via Github several times 😞

**Comment by optimalisatie** [comment]
@migliori @galbaras Thank you for reporting the bug!

The style.tools app was originally quickly developed in two weeks time and is hosted on a [cloudscale.ch development server](https://www.cloudscale.ch/) that is sometimes rebooted or used for testing etc.

The login has been removed so that the full functionality is now accessessible without the login hassle, and since the app is cached locally in a Service Worker, it will continue to work efficiently independent of a webserver.

The critical css generator may be one of the best available, even today, since it was based on PostCSS (very robust CSS parser) and since the output is 'RAW' (no optimizations are done by the generator) so that you can use any other professional CSS optimization solution to achieve the best result possible.

If you have any further questions, let us know!
